sudo: required
branches:
  only:
  - master
language: node_js
script:
- mkdir npm
- for d in */; do cd ${d%?} && pb -c 2 -F ../npm/${d%?}.tgz && cd ..; done;
node_js:
- 10
deploy:
  provider: s3
  access_key_id: 
    secure: fsbKAteUKUF/A7O29JUdfzrMcStlt1NUtWTRseiOUlFZhOnMP49126mndh3OXCuEXoAFHieH8ZajG5mFWahqTTDDNPWFiPUQNgjOV4ZHSwkRiTyyR4FD9jBDgV6vh0792lLhogkGVt6tyYAm5+np3ATAgKIj2EqhtJfghmqZZCbYpXtw6vb23MmGGRj4H3+h51kCs203UDO+IY8MhwLE6wF6HWkxgoQ6zsVGH32swehacyeS737lDML7se0X1XcCwl0sYOhPCuxuBL+v1/DF0I7ks9MImXZD2B2sdf19B7h5KNNOzIUIu3RUtJeDA4kmasazUSw0fZIYkFOZ5Bk/RKKJMIrw5jWUjFaKLlFmLQ4D2Hejk3z8+9XQjqgHfTEEozQnc3G0DvNsT+0SKIuvzTPmip8nFKupxOdQqpuBLw0fCJNirGb0qf+VKiN2x7xh0tcfUHBo1YKU/vVZrLGjpEHexoxkgSqAMBdx+uviUJc3waSrsw0lWPwx6uFA4Ao/pThna28PucCT0ZI0Twyon9IrZFqWug00/WKs6xZlzd5Rvx1PWIoaEPFYKXHiLKh7YleT1bvBMTfvzQ8jqlp79M7h8+O5Ggz8E1ZWRYQhH49bqnmnfPWgu9C+MJFLQpr+RlAPCmJIijBzmJTmAvO1PaKZ48DjDLJqq7NOkjasnYU=
  secret_access_key:
    secure: GFxT4TAnG6u+GwUrtoGi7OPkKNfd03+lC3kijQ5MQIVbf3pNq+56ynB76WdJXDW/qKEphZIc7orz5ROkUSPRb8mfFmJTw8k1ma5eWRGuZtG2VMxkoJdqfoZQXflMEhz1Mlur8UUFyN3my1ngPxiAt6QtgKUchbFpI3Y7WXsTvxsPqfYYYRzlHTj28lc0t5O7ycgJktkqzsbLwPPgSiMnct1M3AMbTQ1Jzg6YQHeuP06chB2eAE4kZzPiOv46+8jiNyripFZmaBlcLaJ5CuR7JxNNz98rMweeCS5dEYwcNiwLi72cvoTpw13snXvzFw6S+iRCRSFv8+vJdRIIBsN9DxsoBzhCTuH0y6u2JqtSXN49UaGmeOpEGq8q6QApN6cog27dAi2ZvQ3cbfSP4/4krzzqk7eNHPbBvHxIvJzewl11zMHN5i7LyB8ZaAHRjm3bZG5lH8lEb62rClTPUmNLCNActlu7tIwIqgXnOhK0vjKzuVLmnLrzJSnrb/EqwnIRJhEz9QQTyxd2JmtdYOz8y0PePa0aszhyEaDb4MTfuCZOqLprLWDSDHcnoiBFWerDjecjRhXjfMBukmLNjEqsE5Z04Jycq5Ja/L+xgFy068Iok0u83t5KsbtrzJJiZaePd9B/H4Py6fJpAwyN0fzCWuEtAQWvyBUsE/gklbIpMSw=
  bucket: deskoh-npm
  skip_cleanup: true
  local_dir: npm
  acl: public_read
before_script:
- npm install -g package-bundle
notifications:
  email: true
  slack:
    rooms:
      secure: ShH2ocqWvFxe72vqWVHvn3SMSl06X5VtVDsP5j8O2vnL+OqdJebJeWY5f71H49BTIOj2Esnk5vGv05zSgETOpXBQTwl6b5TclrnS3SUs8f6/pV58Vgb/VTChv5Arnl3LivxysJJQ//b4+6xuZsXRJf/EDEfTTKX8mA1VitQ+WcLvlANnV0bRk5h5+qQ1cyroh5om16BzybAimtVRJ1nOeO144F5ZqE0Ez08hZh+rNH7dSjqIJEX/VYCrGWI/4lZmZI6sTq8JynhWCEkwtMZ9vhvSSo9ybFiGNw324OGb+n9LcmenGcOdkOwoDGYN2ggwe05bF9iaij6U47jIqKUycCgChynllama7cNCNaTPoHWxWQf/pwZDaUAaRNWZYFnve+rOsXZXy8r05f9f4zk+azI6dBudklYamcJIEfgJto/2KcjgrZkFIZS0f/DPafF6bMRUtKvYeZ6pNNpXLZW2QXxAVrsjA8a9dFgwyHVUPl9cT3ltI+FrwYcA9hAsup/cKhN6MB+L4PxI9ju1E5Q5etdf4TI8dAhjAvqG8osSat2ppPJkWyvNLPmmZ5lWxxlZ0/U1pyertDAVSD+NAaomCX6s1EiILhh+F+ccLLpzFwipGdYpTOy2poxvx1QuS3y+9DG5VcLI8WHHYjKqXKE//GD9K3G+AwGJNLcg7MDtNRE=
