sudo: required
language: node_js
script:
- mkdir npm
- for d in */; do cd ${d%?} && pb -c 5 -F ../npm/${d%?}.tgz && cd ..; done;
node_js:
- 10
deploy:
  provider: s3
  access_key_id:
    secure: b4duj6YG4UL1ICoRzrX+loFtetKclw5z0hVGXO2mczndJnwrATizK+eOowpjgTn5IM4QzeG9XV3PyszUAf/UMNWykDa84Yw67q12qWgVWAZU1zjDkzKKKOhEcZ8sqwmQoX7w0DtNk586/AwkP12Z8NtYKNWkavXfHOvElimv19TTMiWy4c/Z6O5Zt1SEPyIz5ryejDAz6HSBRNs74DJk8WzM63izllCYg26vs1JnMpC5F77kDeU6mdC03zynBbYxwa9+zO/Is1CxBrWniGuo0S+uBZkczhwWW0pbhvVrqu1pvIUVU01paWG37YNTtsfMFGjJwd0wX5oGhq5Ubcll8sKH+ljkwXycaSm4yzvkToNreNWwH0LQ4rfJbs2L+N5SZWPxrt/xgwy59Ep2pj2j6ij/qSUUU2vwdEC1O+7pcpKG0TvrMhNDfzPVD2ozgtSteQyBBLgdIo5qyIEImj5C7Rt7i4Dss3XezuLCKhuNyNKbKFMeZajgmdOAy5mRMggEk2rbdIbHUBgv8xmxTKQHLy+gIWcQBt2TrnpANzRpIpjaXevvq9FjT4XA85Xkn4IsmU+h+Qoc5MVs3n2fFMUoFdaJ3mWXJyfZ0vbImPT90567g/dPhk7fhdyvR3IPemvLYbeWMH8/2/HztvAQK49yLKUjuQEaPXOmHfdrV46pudw=
  secret_access_key:
    secure: KFs7KyzIyfcImxDk9HQaLI+Xy6SLIXNrTKOBx3wD4JEZeCBDxA6zQ93bNcIXKXPLXYIUPCrkOs5iwbvGxuDDBWD+Ms7GeeK1OW3ZNxBl1tPmzEuaWm46tMuEJjZ4aBZnntiIuN5zRP5WXPIBgXBfOgtwK+n73gh/tG/bpQpVy5fjs5zU6GYdoPS7dbrKAB2vtB/TYRZdb7s8Ed3fmpDzddZQKqTcdYdPhyGb/WP8W9HKQviA7byKc380ygDsiV8AfsqVu0fzTCCNppgBXi1VHD9c6npZl5lgw4QbwI8Ny0sDa67YFGBRppmRkXv3iII9exLuRNU5sLf3I7rpRJluknxn+TWsBz2fQ2LFRdseLZSl8+yNKMi05YwvmsD3DosvG/zzue0d1nYpzBpzdkomD+Hb4Lj9DgHAidakOCJFYHxBxKj8vs1KmDJRR9xtJn0hbqkZUjz0VuQ33807keaqVSci2rBSunAHExFw0wBEH3jfJ+oYSnRyQXC/gEynnscNvA+IILOSv8kDT+h7Z3rhF0ano1xkwQ7ZfNo8o6JutF1/Csd6oT17xAe9RtW4agViVgiC42nFu//f93poOepdkyLD7N/cG0+GLpUtiv8xRuxK86kXMfvZ6hhppmqMOS9507TdOIvkEkKHcGfN5StMTvolr4EbEqid8vqwvgxCZAc=
  bucket: deskoh-npm
  skip_cleanup: true
  local_dir: npm
before_script:
- npm install -g package-bundle
notifications:
  email: true
  slack:
    rooms:
      secure: ShH2ocqWvFxe72vqWVHvn3SMSl06X5VtVDsP5j8O2vnL+OqdJebJeWY5f71H49BTIOj2Esnk5vGv05zSgETOpXBQTwl6b5TclrnS3SUs8f6/pV58Vgb/VTChv5Arnl3LivxysJJQ//b4+6xuZsXRJf/EDEfTTKX8mA1VitQ+WcLvlANnV0bRk5h5+qQ1cyroh5om16BzybAimtVRJ1nOeO144F5ZqE0Ez08hZh+rNH7dSjqIJEX/VYCrGWI/4lZmZI6sTq8JynhWCEkwtMZ9vhvSSo9ybFiGNw324OGb+n9LcmenGcOdkOwoDGYN2ggwe05bF9iaij6U47jIqKUycCgChynllama7cNCNaTPoHWxWQf/pwZDaUAaRNWZYFnve+rOsXZXy8r05f9f4zk+azI6dBudklYamcJIEfgJto/2KcjgrZkFIZS0f/DPafF6bMRUtKvYeZ6pNNpXLZW2QXxAVrsjA8a9dFgwyHVUPl9cT3ltI+FrwYcA9hAsup/cKhN6MB+L4PxI9ju1E5Q5etdf4TI8dAhjAvqG8osSat2ppPJkWyvNLPmmZ5lWxxlZ0/U1pyertDAVSD+NAaomCX6s1EiILhh+F+ccLLpzFwipGdYpTOy2poxvx1QuS3y+9DG5VcLI8WHHYjKqXKE//GD9K3G+AwGJNLcg7MDtNRE=
