sudo: required
branches:
  only:
  - master
language: node_js
script:
- mkdir npm
- for d in */; do cd ${d%?} && pb -c 2 -F ../npm/${d%?}.tgz && cd ..; done;
node_js:
- 10
deploy:
  provider: s3
  access_key_id: 
    secure: "XjF6AC6iP9Uzn5xlxbe7P8P7+vvPiA/dKPEUM6cPocXeScuLs4Z5VzY9pQS277NVqOTzEO7NpOTLigR3bXgqdE94K36R6BQFLyEzXj+2OfIKImB1M2WvQ9OIiWrUK6nl+Qald5YhMviyd8Xthmb8ApldpakgJqBz7x+mUM8ZNkdk000ueMOeUF+ACZ04iMp14EVMRRfT0PiM/VorrmyCHsaT1BlnWleAlniMniHxhnsz+8IXMinFg0yACbzR4sG51ekq9oQ7mGcmKXv+uc/a2hU/qFbWfeeA1aSlPtn+UT9vzmK8792ORq/kwWk/ivMNvtvXlC+x2bJKaRyeUu9Fxuhe5Ln/IVGWJHOPtj3OoqLXp5okL5wceZqcUMWtye95U5/cJ3L+3S+6J6n9VFFqCDTI0U/QFpIbk/bFecUyFW1QOFRApx4yf+/2kf4Z9tPP2v5PYfx6nQ+FuqWWr3WSSaSuJrXkkms5eQtxJPwTcrqIp7ZLTZNMZJNd6HaBMUlWdS8Egsw91QTrGpZ/n1oTikbCZRI6sluBgbL6/xewqG0oJJjguzB1FDuBgAtWDmdVScBA/E3jstw03Um6DyEqsy2lCRIK3FS46h9v0KJ9EnShUIvlARb/qyXX3yzcHnim+lhIJpOec3Xr/wT5WBDAvMgGI2iEVZ7ZfdCdd3xsnTU="
  secret_access_key:
    secure: "p/izr96JfEmx4/6HeDtWI/OYurfNcGNccDGMgYbsdj1D4TxNLRWLe0kLG5uY9lZaxOFDPBCI62WRzq2qCk1cz5eYRrCISFdRdlJi7vEa1tATuyykKqejPaJ3Cz2+g95fzo5il0hdUqFlZG6TNdHY6pw2rK7t0QDsr0P7tCnUS/eiqOHWhVPPwOq8X9o+3Wp8hYSbsaUTevhSU/r2ANyWxgiRzHQolIIKA4d2d/jBgzff0p2G3VAeAPLMJ7nF7N/LJwG+VZfccIPg9m0HwLOG5wQ2aYrWLb50ecZ17IlXbbrBgLCqfeFk+Vee2yZiqVsLu7s3HgvYD41DOHtxxgGkRjZ/1CvidtsUfIcRXDyGzYnF5TKyL9q4J69qLES5QpgkDah4BHFAc1qXuc/tCVjnpnAgWs01xj9o0OilAmkokOFzEPnIfRRGxqIWLrsoK9JpKu4O8Mh7ZgSCdm9SM93C82idIPiafeDGaxMCh+YuJmUPVYmrX5R4fjRokNye5GhoDq3tF6rz9i+iBHswcPcRauow00kTxW0AID4OMl4CgZcVEdH6koUDjFamSkixWs6Aj9vpKH3l9VPyTjct9y+VN/jZ/doXmEjOHfYkEuLjbQLsNMKia6RuXKooh6d1L6ePhTfIBH7rva1xwWd27W0xOx+xtfgVFaOOhCnU2SiMo/U="
  bucket: npm-store
  region: ap-southeast-1
  skip_cleanup: true
  local_dir: npm
  acl: public_read
before_script:
- npm install -g package-bundle
notifications:
  email: true
  slack:
    rooms:
      secure: ShH2ocqWvFxe72vqWVHvn3SMSl06X5VtVDsP5j8O2vnL+OqdJebJeWY5f71H49BTIOj2Esnk5vGv05zSgETOpXBQTwl6b5TclrnS3SUs8f6/pV58Vgb/VTChv5Arnl3LivxysJJQ//b4+6xuZsXRJf/EDEfTTKX8mA1VitQ+WcLvlANnV0bRk5h5+qQ1cyroh5om16BzybAimtVRJ1nOeO144F5ZqE0Ez08hZh+rNH7dSjqIJEX/VYCrGWI/4lZmZI6sTq8JynhWCEkwtMZ9vhvSSo9ybFiGNw324OGb+n9LcmenGcOdkOwoDGYN2ggwe05bF9iaij6U47jIqKUycCgChynllama7cNCNaTPoHWxWQf/pwZDaUAaRNWZYFnve+rOsXZXy8r05f9f4zk+azI6dBudklYamcJIEfgJto/2KcjgrZkFIZS0f/DPafF6bMRUtKvYeZ6pNNpXLZW2QXxAVrsjA8a9dFgwyHVUPl9cT3ltI+FrwYcA9hAsup/cKhN6MB+L4PxI9ju1E5Q5etdf4TI8dAhjAvqG8osSat2ppPJkWyvNLPmmZ5lWxxlZ0/U1pyertDAVSD+NAaomCX6s1EiILhh+F+ccLLpzFwipGdYpTOy2poxvx1QuS3y+9DG5VcLI8WHHYjKqXKE//GD9K3G+AwGJNLcg7MDtNRE=
